# Generated by Django 3.1.4 on 2020-12-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20201210_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.CharField(default='Munich', max_length=30),
            preserve_default=False,
        ),
    ]
