# Generated by Django 3.1.4 on 2020-12-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='excerpt',
            field=models.CharField(default='Enjoy the bloodshed !!!!', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='headline',
            field=models.CharField(default='Old School game that every one was waiting for ...', max_length=100),
            preserve_default=False,
        ),
    ]
