# Generated by Django 3.1.4 on 2020-12-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_img', models.ImageField(upload_to='images/')),
                ('name_img', models.ImageField(upload_to='images/')),
                ('alt_text', models.CharField(max_length=50)),
                ('game_title', models.CharField(max_length=50)),
                ('game_description_top', models.CharField(max_length=200)),
                ('game_description_bottom', models.TextField()),
                ('game_system_requirements', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('slide_img_1', models.ImageField(upload_to='images/')),
                ('slide_img_2', models.ImageField(upload_to='images/')),
                ('slide_img_3', models.ImageField(upload_to='images/')),
                ('slide_img_4', models.ImageField(upload_to='images/')),
                ('slide_img_5', models.ImageField(upload_to='images/')),
                ('slide_img_6', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
