# Generated by Django 3.1.4 on 2020-12-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_img', models.ImageField(upload_to='images/')),
                ('name_img', models.ImageField(upload_to='')),
                ('alt_text', models.CharField(max_length=50)),
                ('pup_date', models.DateField(verbose_name='')),
                ('publisher_1', models.CharField(max_length=50)),
                ('publisher_1_anchor', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_img', models.ImageField(upload_to='')),
                ('name_img', models.ImageField(upload_to='')),
                ('alt_text', models.CharField(max_length=50)),
            ],
        ),
    ]
