# Generated by Django 3.1.4 on 2020-12-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_name',
            field=models.CharField(default='game', max_length=50),
            preserve_default=False,
        ),
    ]
