# Generated by Django 3.1.4 on 2020-12-09 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_game_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='pup_date',
            new_name='pub_date',
        ),
        migrations.AlterField(
            model_name='game',
            name='name_img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
