# Generated by Django 3.1.4 on 2020-12-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20201209_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_name',
            new_name='game_title',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='pub_date',
            new_name='release_date',
        ),
        migrations.AddField(
            model_name='game',
            name='background_img',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='game_description',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='platform_1',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='platform_1_anchor',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='platform_2',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='platform_2_anchor',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='platform_3',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='platform_3_anchor',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='publisher_2',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='publisher_2_anchor',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='publisher_3',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='publisher_3_anchor',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='trailer_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='games',
            name='main_img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='games',
            name='name_img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
