# Generated by Django 3.1.4 on 2020-12-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20201209_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='platform_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform_2_anchor',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform_3',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='game',
            name='platform_3_anchor',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher_2',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher_2_anchor',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher_3',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='game',
            name='publisher_3_anchor',
            field=models.URLField(blank=True),
        ),
    ]
