# Generated by Django 3.1.4 on 2020-12-09 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20201209_1537'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Games',
        ),
    ]
