# Generated by Django 3.1.4 on 2020-12-09 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_delete_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_img', models.ImageField(upload_to='images/')),
                ('name_img', models.ImageField(upload_to='images/')),
                ('alt_text', models.CharField(max_length=50)),
            ],
        ),
    ]
