# Generated by Django 3.1.4 on 2020-12-10 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_games'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Games',
        ),
    ]
