# Generated by Django 3.1.4 on 2020-12-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_delete_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_description',
            field=models.TextField(max_length=200),
        ),
    ]
