# Generated by Django 3.1.4 on 2020-12-26 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_auto_20201226_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_description',
            field=models.TextField(),
        ),
    ]
