# Generated by Django 3.1.4 on 2020-12-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20201210_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='place',
            field=models.CharField(default='Berlin', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='new',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
