# Generated by Django 3.1.4 on 2020-12-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20201226_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='excerpt',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
