# Generated by Django 3.1.4 on 2020-12-26 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20201226_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new',
            name='place',
        ),
    ]
